json_transform:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: fipbiwy-mj87522
      user: SHUSHIL
      password: Ganesh@1999
      role: dbt_role
      warehouse: dbt_WH
      database: dbt_DB
      schema: dbt_SCHEMA
      threads: 4
      client_session_keep_alive: false